### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by DualWield** [timqian/star-history#19]
![image](https://cloud.githubusercontent.com/assets/4132470/14805370/d8e9ebde-0b9d-11e6-9513-d2e87e9e2806.png)

我鼠标移在12.13号，但是高亮的点位置不对；
还有如果一段时间star数没有变化的话，应该是一条水平线吧，而不是什么都没有

**Comment by timqian** [comment]
纵坐标的刻度单位是30，在12.13的时候那个项目star 太少，所以没有数据点。
没有设水平线的原因是可能那时候这个项目都还没有

**Comment by timqian** [comment]
第一个 bug 无法重现

**Comment by DualWield** [comment]
你使用chrome，添加我添加的那2个repo，不能复现吗？

**Comment by timqian** [comment]
@DualWield 是的

**Comment by DualWield** [comment]
@timqian 那算了
