### ISSUE TITLE
Search a repo with a URL param

### ISSUE THREAD

**Issue by GaryKing** [timqian/star-history#27]
Is it possible to add a URL param to search that repo, without needing to enter it into the form and submit it?

Such as http://www.timqian.com/star-history/?repo=sass/sass ?

**Comment by timqian** [comment]
Yeah, of course. This feature is in the plan( #25 ). I will find time to implement it soon.

**Comment by timqian** [comment]
I have finished with this feature, Plz check the new version.

**Comment by GaryKing** [comment]
Works great.
