### ISSUE TITLE
sampling the last entry of each page

### ISSUE THREAD

**Issue by clkao** [timqian/star-history#28]
It seems we are currently using the first entry of each page as sample.  If a repo has been quiet lately, the chart will miss data points to the most recent date and look awkward.

**Comment by timqian** [comment]
I am not quiet sure about what you means, Do you have a example?

**Comment by clkao** [comment]
If you put in `datproject/dat.land`, you'll see the latest entry is Oct 2015, because that's the first entry of the last stargazer page.  maybe just add an additional data point for the last entry of the last page?

**Comment by timqian** [comment]
This is a reasonable advice, thanks~
Check the new version.

**Comment by timqian** [comment]
The solution for now is not good enough. I am planning to add a data point for the searching date. See #29
In this way, We can also partially solve another problem: "One can only get the first 40000 star info from github api"
I think I can finish this tomorrow

**Comment by timqian** [comment]
done 10444c35cf2321aaa1a37d0e668aa69fcb727aca
