### ISSUE TITLE
Upper limit

### ISSUE THREAD

**Issue by GaryKing** [timqian/star-history#30]
The charts are only limited to 39960 stars max on the y-axis? Like [here](http://www.timqian.com/star-history/#FreeCodeCamp/FreeCodeCamp). Is that a limitation of the GitHub API or something?

**Comment by mmcev106** [comment]
Here is another example:

http://www.timqian.com/star-history/#angular/angular.js

**Comment by timqian** [comment]
The problem is partially fixed(10444c35cf2321aaa1a37d0e668aa69fcb727aca). Check those links again.

### About the fix
There is an api limit: Github only only allow one to get information of the first 40000 stars.
The way I fix this is to add another point of star number of today.
