### ISSUE TITLE
After clearing graph via "Clear", tooltips are still rendered

### ISSUE THREAD

**Issue by twolfson** [timqian/star-history#33]
Steps to reproduce:

- Added a few repositories to view star history of (e.g. Ensighten/grunt-spritesmith, Ensighten/spritesmith, twolfson/gulp.spritesmith)
- Cleared graph data via "Clear" button
- Moved mouse over former graph area

Expected behavior: No tooltip should appear

Actual behavior: Tooltip for past graph data appeared

Screenshot:

![selection_234](https://cloud.githubusercontent.com/assets/902488/16683268/2d2c269a-44ff-11e6-92cb-b3c36eb3509b.png)

**Comment by timqian** [comment]
Thanks for your repot

**Comment by twolfson** [comment]
And thank you for the great tool =)
