### ISSUE TITLE
Colors do not match up properly in some cases

### ISSUE THREAD

**Issue by mmcev106** [timqian/star-history#43]
At [this url](http://www.timqian.com/star-history/#joomla/joomla-cms&bolt/bolt&anchorcms/anchor-cms&octobercms/october&getgrav/grav&anchorcms/anchor-cms&WordPress/WordPress) the color of the WordPress line on the graph does not match the color of the WordPress line on the stats popup.

**Comment by mmcev106** [comment]
I just realized that url has 'anchorcms/anchor-cms' listed twice.  Fixing that seems to fix the issue, so it seems to be caused by duplicate repos.

**Comment by timqian** [comment]
Yeah, the newer line's color is covering the old one's.
