### ISSUE TITLE
Weird graph on Firefox on Linux

### ISSUE THREAD

**Issue by Compro-Prasad** [timqian/star-history#48]
Firefox latest version.
![star-counter](https://user-images.githubusercontent.com/11143962/46855354-14064d00-ce21-11e8-8910-56ad0a708d09.png)

**Comment by davidjbradshaw** [comment]
Seeing the same on Safari iOS

**Comment by timqian** [comment]
tested in latest firefox and safri for vscode project. this issue should have been fixed
