### ISSUE TITLE
What type of license?

### ISSUE THREAD

**Issue by khoren93** [timqian/star-history#52]
Hi @timqian ,

Thanks for this excellent service.
I would like to know what type of license is provided for this service?
Can I integrate this service in my open source project [SwiftHub](https://github.com/khoren93/SwiftHub)?

Thanks again!
![simulator screen shot - iphone xr - 2019-03-07 at 15 05 25](https://user-images.githubusercontent.com/11523360/53952589-92be9800-40ea-11e9-96fd-2a4ee7479a8f.png)

**Comment by timqian** [comment]
Sure, I will license it as GPLv3 I think
