### ISSUE TITLE
Graph Changes

### ISSUE THREAD

**Issue by asim** [timqian/star-history#53]
Hey. The graphs on the hosted version appear to look slightly different with the new UI. It seems to flat line at the top. Not really an issue but just wanted to highlight that.

**Comment by timqian** [comment]
I think this may because the repo does not get many stars recently. Do you have any example?

**Comment by aeneasr** [comment]
Agreed, but other star plotters are not affected by this, for example: https://starchart.cc/

**Comment by timqian** [comment]
@aeneasr Thanks for providing the starchart.cc example, Some graph do have issues, I will fixed it asap

https://star-history.t9t.io/#pytorch/pytorch

![Screen Shot 2019-04-10 at 3 28 41 PM](https://user-images.githubusercontent.com/5512552/55859963-bff8dd00-5ba5-11e9-9e0b-9c9506b00ae5.png)


https://starchart.cc/pytorch/pytorch
![Screen Shot 2019-04-10 at 3 28 46 PM](https://user-images.githubusercontent.com/5512552/55859877-917b0200-5ba5-11e9-9d1a-3e1f7f736b77.png)

**Comment by timqian** [comment]
<img width="837" alt="Screen Shot 2019-04-15 at 10 20 29 AM" src="https://user-images.githubusercontent.com/5512552/56103977-26944700-5f68-11e9-8168-0fccb442472c.png">

this issue is fixed in  35789d5
