### ISSUE TITLE
x coordinate is always 0 in Firefox

### ISSUE THREAD

**Issue by kachkaev** [timqian/star-history#63]
__To reproduce:__

1. Open Firefox 69.0.3 (latest)
2. Navigate to https://star-history.t9t.io/#timqian/star-history
3. Observe the following chart:

<img width="982" alt="Screenshot 2019-10-12 at 13 31 36" src="https://user-images.githubusercontent.com/608862/66701516-cb63c700-ecf4-11e9-99cd-ddaff22c71ea.png">

Console says `Unexpected value NaN parsing cx attribute.`

The same page renders well in the latest Chrome.

**Comment by TheLocehiliosan** [comment]
Same problem occurs in Safari.

**Comment by timqian** [comment]
Thanks for pointing it out, this bug has been fixed in https://github.com/timqian/star-history/commit/56e7ed1f855888a790d5441f53facf5dde981bda

**Comment by kachkaev** [comment]
Thank you for looking into the problem @timqian. After deep-refereshing the page in FF, I can confirm that the chart works for me! 🎉
