### ISSUE TITLE
"No such repo" for any repo

### ISSUE THREAD

**Issue by oprogramador** [timqian/star-history#67]
- I open https://star-history.t9t.io/
- I type any repo name e.g. `timqian/star-history`
- it shows `No such repo`

<img width="1278" alt="Screenshot 2020-02-03 at 00 19 15" src="https://user-images.githubusercontent.com/8701039/73617037-fb740480-461a-11ea-8bdc-30f30ed107ec.png">

**Comment by timqian** [comment]
seems the repo path you entered is wrong, there should be no space. e.g. `timqian/star-history` instead of `timqian / star-history`

**Comment by oprogramador** [comment]
Thanks, I didn't notice copying it from GitHub inserts spaces.
It would be nice if https://star-history.t9t.io/ deleted spaces automatically but it's low priority for me . I can always copy a part of the given repo URL so I don't need to remove spaces.

**Comment by timqian** [comment]
entering the whole url directly also works. it extracts repo path automatically~
