### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by tom-doerr** [timqian/star-history#71]
Could you add a license to the project?
I bought your browser extension to support you and your project but just noticed that this isn't free software, which makes me somewhat uncomfortable.

**Comment by waldyrious** [comment]
@tom-doerr good point. According to the [package.json](https://github.com/timqian/star-history/blob/46dff95e626263334bb771906eda61baa9b46900/package.json#L22) this is licensed under MIT, but the license file with the [actual license text](https://choosealicense.com/licenses/mit/) needs to be added. A PR adding a `LICENSE` file would be sufficient to fix this AFAIK.
