### ISSUE TITLE
GitHub "User" Star History?

### ISSUE THREAD

**Issue by chonyy** [timqian/star-history#93]
Hi,

I love this project so much.
However, I'm just wondering is it possible to track the history of stars given to a **user** and not a repo?
As I know, there's no stargazer list for a specific user.
So, I'm not really sure if it's possible.
I would really like to know how could we track it.

Any idea would be nice.

Thanks.

**Comment by timqian** [comment]
Hi @chonyy this is a nice idea

The way I can think of is like this
1. get all the repos of a user
2. get the star history of each repo
3. add up all the stars

We will need to take care of GitHub rate limit too https://docs.github.com/en/developers/apps/rate-limits-for-github-apps
